// src/components/footer.tsx
import Link from "next/link";

export const Footer = () => {
    return (
        <div className="flex items-center justify-center px-4 pb-6 pt-12 text-center text-sm text-zinc-400 xl:px-8 xl:pb-6 xl:pt-2">
            <p>
                <Link
                    href="https://beyourahi.com"
                    target="_blank"
                    className="group sleek"
                >
                    Designed by <span className="group-hover:text-white group-hover:underline underline-offset-4">@beyourahi</span>
                </Link>
            </p>
        </div>
    );
};

// src/lib/components/ui/footer/footer.svelte
<!--
  Footer Component
  Displays developer attribution with link
  Responsive padding and typography
-->
<script lang="ts">
    import { APP_CONFIG } from "$lib/config";
</script>

<footer
    class="flex items-center justify-center px-4 py-6 text-center text-xs text-zinc-500 sm:px-6 sm:py-8 sm:text-sm"
>
    <p>
        <a href={APP_CONFIG.author.url} target="_blank" rel="noopener noreferrer" class="group sleek">
            Designed by
            <span class="underline-offset-4 group-hover:text-white group-hover:underline">
                {APP_CONFIG.author.name}
            </span>
        </a>
    </p>
</footer>
