// src/components/heading.tsx
export const Heading = () => (
    <div className="space-y-8 text-center">
        <p className="text-5xl">🚀</p>

        <div className="space-y-2">
            <h1 className="text-3xl font-black lg:text-4xl">Shopify Order Processor</h1>
            <p className="text-zinc-400">Turn Chaos into Orders</p>
        </div>
    </div>
);

// src/lib/components/ui/heading/heading.svelte
<div class="space-y-4 text-center sm:space-y-6 lg:space-y-8">
    <p class="text-4xl sm:text-5xl">🚀</p>

    <div class="space-y-1.5 sm:space-y-2">
        <h1 class="text-2xl font-black tracking-tight sm:text-3xl lg:text-4xl">Shopify Order Processor</h1>
        <p class="text-xs text-zinc-400 sm:text-sm lg:text-base">Turn Chaos into Orders</p>
    </div>
</div>
