// src/lib/components/ui/footer/footer.svelte
<!--
  Footer Component
  Displays developer attribution with link
  Responsive padding and typography
-->
<script lang="ts">
    import { APP_CONFIG } from "$lib/config";
</script>

<footer
    class="flex items-center justify-center px-4 py-6 text-center text-xs text-zinc-500 sm:px-6 sm:py-8 sm:text-sm"
>
    <p>
        <a href={APP_CONFIG.author.url} target="_blank" rel="noopener noreferrer" class="group sleek">
            Designed by
            <span class="underline-offset-4 group-hover:text-white group-hover:underline">
                {APP_CONFIG.author.name}
            </span>
        </a>
    </p>
</footer>

// components/footer.tsx
import Link from "next/link";

export const Footer = () => {
    const year = new Date().getFullYear();

    return (
        <div className="flex flex-col items-center justify-center gap-6 px-4 pb-8 pt-12 text-center text-sm text-zinc-400 sm:flex-row sm:justify-between xl:px-8 xl:pb-12 xl:pt-2">
            <p>Copyright &copy; {year}</p>

            <p className="flex flex-col items-center gap-1 sm:items-end">
                <span>
                    <Link
                        href="https://beyourahi.com"
                        target="_blank"
                        className="sleek underline underline-offset-4 active:text-zinc-300 active:underline-offset-[6px] xl:hover:text-zinc-300 xl:hover:underline-offset-[6px]"
                    >
                        Rahi Khan
                    </Link>{" "}
                    appreciates you using this app.
                </span>

                <span>Happy processing orders! 🥳</span>
            </p>
        </div>
    );
};
