// components/courier-picker.tsx
import { useContext } from "react";
import Image from "next/image";
import { cn } from "lib";
import pathao from "public/pathao.png";
import steadFast from "public/steadfast.png";
import redx from "public/redx.png";
import sheba from "public/sheba.jpg";
import ecourier from "public/ecourier.webp";
import dhl from "public/dhl.png";
import fedex from "public/fedex.jpeg";
import { Context } from "app/providers";
import { Button } from "./ui/button";

const COURIER_OPTIONS = [
    { value: "Pathao", label: "Pathao", logo: pathao },
    { value: "SteadFast", label: "SteadFast", logo: steadFast },
    { value: "REDX", label: "REDX", logo: redx, coming_soon: true },
    { value: "Sheba", label: "Sheba", logo: sheba, coming_soon: true },
    { value: "eCourier", label: "eCourier", logo: ecourier, coming_soon: true },
    { value: "FedX", label: "FedX", logo: fedex, coming_soon: true },
    { value: "DHL", label: "DHL", logo: dhl, coming_soon: true }
];

export const CourierPicker = () => {
    const { courierService, setCourierService } = useContext(Context);

    return (
        <div className="items flex h-80 w-full flex-col gap-4 rounded-xl bg-white/10 p-2 text-left text-white drop-shadow-xl lg:w-1/2">
            <div className="flex flex-col overflow-y-scroll">
                {COURIER_OPTIONS.map(({ value, label, logo, coming_soon }) => (
                    <Button
                        disabled={coming_soon}
                        key={value}
                        size="lg"
                        onClick={() => setCourierService(value)}
                        className={cn(
                            "sleek m-2 cursor-pointer justify-start gap-4 rounded-[0.7rem] py-7 pl-4 font-semibold shadow-none",
                            courierService === value
                                ? "bg-green-400/30! ring-3 ring-green-400 active:bg-green-400/30! xl:hover:bg-green-400/30!"
                                : "bg-white/10 active:scale-95 active:bg-green-400/20! xl:hover:bg-green-400/20!",
                            coming_soon && "cursor-not-allowed bg-white/5 opacity-50"
                        )}
                    >
                        <Image src={logo} alt={label} className="h-7 w-7 rounded-full object-cover" />

                        <div className="flex items-center gap-2">
                            <span>{label}</span>
                            {coming_soon && <span>(COMING SOON)</span>}
                        </div>
                    </Button>
                ))}
            </div>
        </div>
    );
};

// src/lib/components/features/courier-picker.svelte
<script lang="ts">
    import { COURIER_OPTIONS } from "$lib/config";
    import { cn } from "$lib/utils";
    import Check from "@lucide/svelte/icons/check";

    interface Props {
        selectedCourier: string;
        onSelect: (courier: string) => void;
    }

    let { selectedCourier, onSelect }: Props = $props();
</script>

<div class="flex w-full max-w-sm flex-col items-center gap-4 sm:gap-6">
    <div class="flex w-full flex-col gap-3 sm:gap-4">
        {#each COURIER_OPTIONS as option (option.value)}
            {@const isSelected = selectedCourier === option.value}

            <button
                onclick={() => onSelect(option.value)}
                class={cn(
                    "sleek group relative flex w-full touch-manipulation cursor-pointer flex-col items-center gap-3 rounded-2xl p-4 sm:gap-4 sm:p-6",
                    "ease-[var(--ease)] border border-solid transition-all duration-200",
                    "ring-offset-background focus-visible:ring-ring focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2",
                    isSelected
                        ? "border-courier-accent/60 bg-courier-accent/10 shadow-courier-accent/10 shadow-lg"
                        : "border-border bg-card hover:border-border-strong hover:bg-secondary/60",
                    "active:scale-[0.97]"
                )}
            >
                <div
                    class={cn(
                        "absolute top-3 right-3 flex h-5 w-5 items-center justify-center rounded-full border-2 border-solid transition-all duration-200 sm:h-6 sm:w-6",
                        isSelected
                            ? "border-courier-accent bg-courier-accent"
                            : "border-border-strong group-hover:border-muted-foreground bg-transparent"
                    )}
                >
                    {#if isSelected}
                        <Check class="text-background h-3 w-3 sm:h-3.5 sm:w-3.5" strokeWidth={3} aria-hidden="true" />
                    {/if}
                </div>

                <div
                    class={cn(
                        "flex h-14 w-14 items-center justify-center rounded-xl p-2 transition-all duration-200 sm:h-16 sm:w-16",
                        isSelected ? "bg-courier-accent/15" : "bg-secondary/50 group-hover:bg-border-strong/50"
                    )}
                >
                    <img
                        src={option.logo}
                        alt={option.label}
                        class={cn(
                            "h-full w-full object-contain transition-all duration-200",
                            !isSelected && "opacity-70 group-hover:opacity-100"
                        )}
                    />
                </div>

                <span
                    class={cn(
                        "text-sm font-semibold whitespace-nowrap transition-colors duration-200 sm:text-base",
                        isSelected ? "text-foreground" : "text-muted-foreground group-hover:text-foreground"
                    )}
                >
                    {option.label}
                </span>
            </button>
        {/each}
    </div>
</div>
